- requirement: 1
  name: Implementation
  title: A DGGS specification SHALL include a DGGS Reference Frame and the associated Functional Algorithms as defined by the DGGS Core Conceptual Data Model.
- requirement: 2
  name: Global Coverage
  title: Domain completeness – the DGGS Domain of the initial discrete global grid SHALL cover the entire globe.
- requirement: 3
  name: No Overlapping DGGS Cells
  title: Position uniqueness – the initial discrete global grid SHALL be defined without any overlapping DGGS Cells.
- requirement: 4
  name: Multiple Resolutions
  title: A DGGS specification SHALL comprise a sequence of discrete global grid tessellations representing multiple spatial resolutions
- requirement: 5
  name: Area Preservation for all Resolutions
  title: For each successive level of grid refinement, a DGGS specification SHALL preserve Domain completeness and position uniqueness.
- requirement: 6
  name: DGGS Cells are Simple Polygons
  title: For each successive level of grid refinement, a DGGS specification SHALL define DGGS Cells that are simple polygons.
- requirement: 7
  name: DGGS Cell Area Precision Defined
  title: For each successive level of grid refinement, a DGGS specification SHALL specify a DGGS equal area precision that represents the maximum allowed ratio of cell area uncertainty to cell area
- requirement: 8
  name: Equal Area Cells for each Geometry Type
  title: For each successive level of grid refinement, and for each cell geometry, a DGGS specification SHALL define DGGS Cells that are equal area (or iteratively and predictably converge on equal area) within the specified level of precision
- requirement: 9
  name: Initial Tessellation has Equal Area Cells
  title: A DGGS specification SHALL include an initial tessellation that is defined by equal area cells produced by mapping a base unit polyhedron to the surface model of the Earth.
- requirement: 10
  name: Has Cell Refinement Method
  title: A DGGS specification SHALL have a method to refine parent cells into finer resolution child cells.
- requirement: 11
  name: Can Assign Unique Spatial Reference to Each Cell
  title: A DGGS specification SHALL use a spatial referencing method to assign a unique spatial reference (or index) to each DGGS cell across the entire DGGS Domain.
- requirement: 12
  name: Unique Index for each Cell
  title: A DGGS specification SHALL define a unique index to address each cell across all defined spatial resolutions
- requirement: 13
  name: Cell Referenced at Centroid
  title: A DGGS specification SHALL define the location of a DGGS Cell reference to be the centroid of each cell.
- requirement: 14
  name: Quantization Method(s) for Assigning Data to Each Cell
  title: A DGGS specification SHALL define quantization methods for assigning data to DGGS cells and retrieval methods for reading data from DGGS cells.
- requirement: 15
  name: Methods to Perform Heirarchy and Neighbourhood Naviagation
  title: A DGGS specification SHALL define functions/methods to perform both hierarchy and neighbourhood navigation operations across its entire domain.
- requirement: 16
  name: Method(s) to Perform Simple Spatial Analysis Operations
  title: A DGGS specification SHALL define functions/methods to perform simple spatial analysis operations across its entire domain. [ISO 19125-1:2004] SHALL be used as a basis for specifying the spatial relationship operands that support these functions.
- requirement: 17
  name: Method(s) to Read, Interpret and Execute Data Queries
  title: A DGGS specification SHALL define a method, or functional algorithm, to read, interpret and execute an external data query.
- requirement: 18
  name: Method(s) to Translate Query Results to Standard Data Formats
  title: A DGGS specification SHALL define a method, or functional algorithm, to translate data query/process results from internal DGGS data structures to standard data formats and to transmit/broadcast the reformatted result set via standard data transfer protocols.
