- 实现方法
- DGGS参考范围
- 全球覆盖
- 无重叠DGGS单元格
- 多重分辨率
- 所有分辨率下面积能够维持
- DGGS单元格为简单多边形
- 既定的DGGS单元格面积精度
- 各种几何类型下均为等面积单元格
- 初始镶嵌拥有等面积单元格
- 拥有单元格精细化的方法
- 能够为每个单元格分配独特的空间参考
- 每个单元格的独特索引
- 以形心作为参考的单元格
- 为每个单元格赋值的量化方法
- 执行阶层和邻域导航的方法
- 执行简单空间分析操作的方法
- 读取、解析和执行数据查询的方法
- 翻译查询结果至标准数据格式的方法
